# file: C:\Users\mateo\AppData\Roaming\Python\Python312\site-packages\psutil\_compat.py
# hypothesis_version: 6.135.26

[100, '1234', 'CPython', 'CacheInfo', 'ChildProcessError', 'FileExistsError', 'FileNotFoundError', 'InterruptedError', 'PATH', 'PATHEXT', 'PY3', 'PermissionError', 'ProcessLookupError', '__', 'b', 'basestring', 'currsize', 'errno', 'get_terminal_size', 'hashvalue', 'hh', 'hits', 'latin-1', 'long', 'lru_cache', 'maxsize', 'misses', 'perm', 'range', 'redirect_stderr', 'super', 'u', 'unicode', 'unicode_escape', 'which', 'win32']