# file: C:\Users\mateo\AppData\Roaming\Python\Python312\site-packages\IPython\extensions\storemagic.py
# hypothesis_version: 6.135.26

['%-', '<unavailable>', '>', '>>', "Stored '%s' (%s)", 'The error was:', '__main__', '__name__', '_dh', 'a', 'autorestore/', 'autorestore/*', 'd', 'dhist', 'drz', 'r', 's -> %s', 'stored_aliases', 'string', 'utf-8', 'w', 'z']