# file: C:\Users\mateo\AppData\Roaming\Python\Python312\site-packages\zmq\error.py
# hypothesis_version: 6.135.26

['.', 'Again', 'ContextTerminated', 'Feature', 'NotDone', 'ZMQBaseError', 'ZMQBindError', 'ZMQError', 'ZMQVersionError', 'ignored']