# file: C:\Users\mateo\AppData\Roaming\Python\Python312\site-packages\jupyter_client\launcher.py
# hypothesis_version: 6.135.26

[134217728, 'IPY_INTERRUPT_EVENT', 'JPY_INTERRUPT_EVENT', 'JPY_PARENT_PID', 'PATH', 'close_fds', 'creationflags', 'cwd', 'env', 'launch_kernel', 'pythonw.exe', 'start_new_session', 'stderr', 'stdin', 'stdout', 'w', 'win32']